### ISSUE TITLE
In the file validation method, the passed in 'required' value is not checked

### ISSUE THREAD

**Issue by Griffin6** [spindogs/wp-platform#1]
Recommend line 1429 be changed to:
`if (($required && $this->isRequired($name)) && !$value && !$initial) {`

https://github.com/spindogs/wp-platform/blob/f8e24a729574ae37dd0e0ab4edfe85fac422c6f9/classes/Form.php#L1429

**Comment by ol1s** [comment]
I'm not sure this is necessary because all the field parameters are set in

https://github.com/spindogs/wp-platform/blob/f8e24a729574ae37dd0e0ab4edfe85fac422c6f9/classes/Form.php#L1342

and then `$this->isRequired($name)` uses these field parameters

https://github.com/spindogs/wp-platform/blob/f8e24a729574ae37dd0e0ab4edfe85fac422c6f9/classes/Form.php#L2056

@Griffin6 Please can you describe the scenario whereby this is not working?

**Comment by Griffin6** [comment]
When I used the file function as below, it still deemed the field as required:
`$this->form->file('_banner_pic', 'Upload Banner Picture', false);`
There may be a better solution?

**Comment by ol1s** [comment]
I think it's just an issue with your usage - the signature for the method is:

https://github.com/spindogs/wp-platform/blob/6c282eaf2c0d1b8f1c3dad814ec272530da86bc2/classes/Form.php#L1336

with the third parameter being `$initial` not `$required`
